### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by nahue**
Updates peer dependencies so it can be installed in Angular 9 without warnings

### CODE REVIEW

**Comment by mroloux** [comment]
Do you think we should switch to Angular 9 in our test app as well? Currently it's set to Angular 7.2

**Comment by nahue** [comment]
But that would involve upgrading the compiler as well.. and that might break backwards compatibility

**Comment by mroloux** [comment]
Backwards compatibility? Is that an issue for the test app?

**Comment by mroloux** [comment]
Ideally we should have 2 test apps - one one Angular 7, and one on Angular 9. That way we can easily test whether changes to the client still work on old and new Angular versions.

**Comment by nahue** [comment]
Of course but if you take a look.. testApp does not have a package.json file.. it uses the main one... so it uses the same dependencies from seatsio-angular.

**Comment by mroloux** [comment]
Yes, but I think we only push the built seatsio-angular subproject to npmjs. Which is just the client,  not the sample project.

So we're free to upgrade the Angular version used by our sample project. Or create another one next to it.

Unless I'm missing something?

**Comment by nahue** [comment]
The problem is that Angular treats this as a whole project.. with a library (seatsio-angular) and a app (testApp) but it uses the same dependencies for both. What we could do.. is create a monorepo with lerna, and inside create the angular project.. and as siblings.. two more with different versions. (thats too much effort for this i know)

**Comment by mroloux** [comment]
Approving - let's do a followup PR to upgrade the Angular version

**Pull request merged**
